on:
  push:
    branches:
      - main

jobs:
  build: 
    name: build app
    runs-on: ubuntu-latest
    steps: 
      - name: menampilkan teks
        run: echo "ini step build"

  test: 
    name: test app
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: menampilkan teks
        run: echo "ini step test"

  deployment: 
    name: deploy app
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: menampilkan teks
        run: echo "ini step deployment"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo rm -rf /var/www/html/.git
            sudo rm -rf /var/www/html/.github  
            sudo git clone https://github.com/HindiaGenius/Web /var/www/html/
